### ISSUE TITLE
could you make a flatpak for ValaSimpleHTTPServer?

### ISSUE THREAD

**Issue by ghost** [bcedu/ValaSimpleHTTPServer#10]
Hi, I really appreciate your work , is a very good application
but i don't use elementary OS
could you make a flatpak for ValaSimpleHTTPServer?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by bcedu** [comment]
I will do it. It will be the next release of the app

**Comment by bcedu** [comment]
@chemel9 Ypu can get the flatpak here:

https://flathub.org/apps/details/com.github.bcedu.valasimplehttpserver

Install with:

`flatpak install flathub com.github.bcedu.valasimplehttpserver`
