### ISSUE TITLE
Icon does not meet human interface guidelines

### ISSUE THREAD

**Issue by theotheroracle** [bcedu/ValaSimpleHTTPServer#18]
[Do's and Don'ts of Iconography](https://elementary.io/docs/human-interface-guidelines#dos-donts)

> Dos and Don'ts
> 
> Below are some "do and don't" examples to consider when creating icons for your app.
> 
>     Your icon should not be overly complicated. Keep in mind that since there are smaller sizes, the elements that make up your icon should be distinguishable when at those sizes.
> 
>     Your icon should make use of transparent elements, and should not simply be full-frame images. Where you can, distinguish your icon with subtle yet appealing visuals.
> 
>     Don't make a thin icon. Your icon's weight should be comparable to that of other icons. An overly thin icon won't stand out well on many backgrounds.
> 
>     If you would like to give your icon a tilted perspective, it should tilt backward (not forward).
> 
>     Avoid simply slapping an element onto a base shape; use a unique outline to make your icon more distinct.
>     Take care to properly add light and shadow to inset or extrude foreground elements.
>

**Comment by bcedu** [comment]
Closed by https://github.com/bcedu/ValaSimpleHTTPServer/pull/19

**Comment by theotheroracle** [comment]
i wanna apoligize for this issue, didn't really think of it at the time but this issue was pretty rude, really sorry about that .
