### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by ezeveliz** [bcedu/ValaSimpleHTTPServer#26]
Streaming a movie causes really high RAM usage, it starts growing until it takes the whole RAM and swap, and then it crashes.

RAM consumption:

![Captura de pantalla de 2019-11-19 20-30-07](https://user-images.githubusercontent.com/24837065/69195936-d7b91c00-0b0b-11ea-8b04-53ecdede5a43.png)

Specs:

![System Information](https://user-images.githubusercontent.com/24837065/69196108-4f874680-0b0c-11ea-811c-be7de3ba90fa.png)

**Comment by bcedu** [comment]
Do you know any way to limit the ram usage from the code?

**Comment by ezeveliz** [comment]
I'll take a look

Ezequiel Veliz

El 20 nov. 2019 3:05, Eduard Berloso Clarà <notifications@github.com> escribió:

Do you know any way to limit the ram usage from the code?
