### ISSUE TITLE
not accessible due to IP6?

### ISSUE THREAD

**Issue by elementarynoob** [bcedu/ValaSimpleHTTPServer#29]
Hi, 
unfortunately (and sorry for not knowing how to fix that) I am trying to share files in the same WIFI. 

However, other than the app pictures indicate a short link with 192.168.0.....:8888, the app is using an IP6 link which is not only a challenge to enter into a browser, but also not successful when trying to open.

Please advice.

**Comment by Hedronmx** [comment]
I disabled ipv6 using this guide

https://support.purevpn.com/how-to-disable-ipv6-linuxubuntu
