### ISSUE TITLE
VServer using not longer supported runtime

### ISSUE THREAD

**Issue by costaht** [bcedu/ValaSimpleHTTPServer#32]
Recently I started getting this error message during flatpacks update:

`
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
`
```
sudo flatpak list --app  --app-runtime org.gnome.Platform//3.34
Name            Application ID                                Version        Branch        Installation
VServer         com.github.bcedu.valasimplehttpserver         1.3.5          stable        system
```

**Comment by bcedu** [comment]
Closed by https://github.com/elementary/appcenter-reviews/pull/265
