### ISSUE TITLE
Invalid dconf migration path

### ISSUE THREAD

**Issue by danirabbit** [bcedu/ValaSimpleHTTPServer#35]
Looks like this might be a copy/paste error?

```
  - '--metadata=X-DConf=migrate-path=/org/gnome/dictionary/'
```

**Comment by bcedu** [comment]
Yes, srry. Solved with https://github.com/bcedu/ValaSimpleHTTPServer/commit/8c07756e5e9f09a38ef0e2c167c65b3e720816c7
