### ISSUE TITLE
Update appdata description for Flatpak

### ISSUE THREAD

**Issue by danirabbit** [bcedu/ValaSimpleHTTPServer#36]
```
<p>It also works throught comand line options. Try typing 'com.github.bcedu.valasimplehttpserver --help' to learn more.</p>
```

You probably need to append `flatpak run` here to make sure this is still valid

**Comment by bcedu** [comment]
Closed by https://github.com/bcedu/ValaSimpleHTTPServer/commit/b6bf349520ab204ceca3fa3fb36343637abb3c77
