### ISSUE TITLE
Use FileChooserNative instead of FileChooserDialog

### ISSUE THREAD

**Issue by danirabbit** [bcedu/ValaSimpleHTTPServer#37]
https://github.com/bcedu/ValaSimpleHTTPServer/blob/77b544ba2cb904126983e21bfd3f7a279c795617/src/views/InitialView.vala#L32

Apps should use [`Gtk.FileChooserNative`](https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html) instead of creating their own file chooser dialog. The native function uses the file chooser portal, so you'll get the correct file chooser provided by Files instead of the old GTK-style dialog and this works without having to request elevated permissions

**Comment by bcedu** [comment]
Closed by https://github.com/bcedu/ValaSimpleHTTPServer/commit/d7fda647efb23d681d93b277fa18e294b6031227
