### ISSUE TITLE
Show QR code

### ISSUE THREAD

**Issue by kdwk** [bcedu/ValaSimpleHTTPServer#38]
After creating a link, a QR code should be shown to let phone/ tablet users (on the same network) access the files by scanning the QR code. It should be much faster than typing the IP address on a phone/ tablet on-screen keyboard.

**Comment by bcedu** [comment]
Good idea! I will try to implement it

**Comment by bcedu** [comment]
Closed with https://github.com/bcedu/ValaSimpleHTTPServer/commit/bd2d30926dad5d6f794e11657087c43fe9fc3786
