### ISSUE TITLE
Not getting system IP address

### ISSUE THREAD

**Issue by iguys** [bcedu/ValaSimpleHTTPServer#41]
Using on Elementary OS 6.1 but its not getting my system IP address and also every time it need to change the listing port number, it not saving it. its generating URL  like this " http://1602:3b04:2e67:9100:417c:13af:127e:682f:8888"

**Comment by bcedu** [comment]
It looks like it's getting the IPv6 addres instead of IPv4 (related? https://github.com/bcedu/ValaSimpleHTTPServer/issues/29)

**Comment by amka** [comment]
@bcedu  Confirm, it shows IPv6.

**Comment by bcedu** [comment]
This should be solved with https://github.com/bcedu/ValaSimpleHTTPServer/commit/084c9c0903fd2284cdf551da3d8f44d2f78c7738

Once the new version is published you will be able to test it.

**Comment by iguys** [comment]
@bcedu Thanks for fixing the issue
