### ISSUE TITLE
Can only have one default screenshot

### ISSUE THREAD

**Issue by cassidyjames** [bcedu/ValaSimpleHTTPServer#8]
All of your screenshots are marked as "default" which makes them not appear in any predictable order in AppCenter.

https://github.com/bcedu/ValaSimpleHTTPServer/blob/39a90f46c3d11d1edb8cfbc22ead8e341cdad150/data/com.github.bcedu.valasimplehttpserver.appdata.xml#L24-L32

**Comment by bcedu** [comment]
Closed by 9444c010e2874ce060bdd0da7f824c63f3ed407f
