### ISSUE TITLE
Make the app translatable

### ISSUE THREAD

**Issue by NathanBnm** [bcedu/ValaSimpleHTTPServer#9]

**Comment by TheNightmanCodeth** [comment]
This would be pretty easy to do. If you have some experience in programming just fork the project, wrap strings like this: `string field_name = _("the string value");` in parentheses with the underscore in front `_()` and bada bing bada boom we can make some `po` files in different languages.

**Comment by NathanBnm** [comment]
@TheNightmanCodeth you're right, I know how to generate the po files but I don't know how to add translations to the build.

**Comment by bcedu** [comment]
@NathanBnm I will do it sonn

**Comment by bcedu** [comment]
Closed with 90767fbef76564a11126ab79d7a31f8e8c54dce2
